const DEFAULT_ICON_COLOR = '#fff'
const DEFAULT_ICON_SIZE = 24
const DEFAULT_ICON_BG_COLOR = '#555555'
const DEFAULT_ICON_INACTIVE_COLOR = '#777777'

const DEFAULT_ICON = {
	COLOR: DEFAULT_ICON_COLOR,
	INACTIVE_COLOR: DEFAULT_ICON_INACTIVE_COLOR,
	SIZE: DEFAULT_ICON_SIZE,
	BG_COLOR: DEFAULT_ICON_BG_COLOR,
}

export default DEFAULT_ICON
