const DEFAULT_ICON_COLOR = '#fff'
const DEFAULT_ICON_SIZE = 24
const DEFAULT_ICON_BG_COLOR = '#555555'
const DEFAULT_ICON_INACTIVE_COLOR = '#777777'
const DEFAULT_ICON_FILL_COLOR = '#3B5998'
const DEFAULT_ICON_ACCENT_COLOR = '#2279CE'
const DEFAULT_ICON_BG_OPACITY = 0.5
const DEFAULT_ICON_CIRCLE_OPACITY = 0.5
const DEFAULT_ICON_OUTLINE_COLOR = '#E2E2E2'

const DEFAULT_ICON = {
	COLOR: DEFAULT_ICON_COLOR,
	INACTIVE_COLOR: DEFAULT_ICON_INACTIVE_COLOR,
	SIZE: DEFAULT_ICON_SIZE,
	BG_COLOR: DEFAULT_ICON_BG_COLOR,
	FILL_COLOR: DEFAULT_ICON_FILL_COLOR,
	ACCENT_COLOR: DEFAULT_ICON_ACCENT_COLOR,
	BG_OPACITY: DEFAULT_ICON_BG_OPACITY,
	CIRCLE_OPACITY: DEFAULT_ICON_CIRCLE_OPACITY,
	OUTLINE_COLOR: DEFAULT_ICON_OUTLINE_COLOR,
}

export default DEFAULT_ICON
